name: Apply MPE Partner Workload Spoke terraform plan

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Apply a plan for an MPE Partner Workload Spoke terraform configuration
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_PROD_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: MPE Workload Spoke terraform apply
        uses: azurenoops/terraform-github-actions/terraform-apply@v1.34.2
        with:
          path: src/modules/workload_spoke
          variables: |
            subscription_id  = "${{ github.event.inputs.workload_subscription_id }}"
            workload_name    = "${{ github.event.inputs.workload_name }}"
            hub_virtual_network_id = "${{ github.event.inputs.hub_resource_id }}"
            firewall_private_ip = "${{ github.event.inputs.firewall_private_ipaddress }}"
          var_file: |
            src/tfvars/production/parameters.dev.gsa.spoke.tfvars