name: Destroy MPE Partner plan [USE WITH CAUTION]

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:    
    runs-on: ubuntu-latest
    name: Destroy terraform configuration plan for an MPE Partner terraform configuration
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_PROD_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform destroy
        uses: azurenoops/terraform-github-actions/terraform-destroy@v1.34.2
        with:
          path: src
          variables: |
            subscription_id_hub               = "${{ env.ARM_SUBSCRIPTION_ID }}"
            subscription_id_partners_gsa_dev  = "${{ secrets.AZURE_PARTNER_GSA_DEV_SUBSCRIPTION_ID }}"
            subscription_id_partners_gsa_prod = "${{ secrets.AZURE_PARTNER_GSA_PROD_SUBSCRIPTION_ID }}"           
          var_file: |
            tfvars/production/parameters.prod.tfvars
          backend_config: |
            storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
            container_name=${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}            
            resource_group_name=${{ secrets.TFSTATE_RG }}
