name: Validate MPE Policy changes 

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  fmt-check:
    runs-on: ubuntu-latest
    environment:
        name: Dev
    name: Check formatting of MPE Partner Workload Spoke terraform configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform fmt
        uses: azurenoops/terraform-github-actions/terraform-fmt-check@v1.34.2
        with:
          path: src

  validate:
    runs-on: ubuntu-latest
    environment:
        name: Dev
    name: Validate MPE Partner Workload Spoke terraform configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform validate
        uses: azurenoops/terraform-github-actions/terraform-validate@v1.34.2
        with:
          path: src
          variables: |
            subscription_id_hub = "${{ env.ARM_SUBSCRIPTION_ID }}"
            subscription_id_partners_gsa_dev  = "${{ secrets.AZURE_PARTNER_GSA_DEV_SUBSCRIPTION_ID }}"          
          var_file: |
            tfvars/parameters.gsa.tfvars
          backend_config: |
            storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
            container_name=${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}            
            resource_group_name=${{ secrets.TFSTATE_RG }}
